Repository GSG-G10/udrive-car-rental, pull requests merged in 2021-11, with the labels that each got.

#129 fix bug validation error
  client/.eslintrc.js
  server/.eslintrc.json
  server/controllers/review/addReviewToCar.js
  server/test/reviews.test.js
  server/utils/validation/addCarValidation.js
  server/utils/validation/commentAndRateValidation.js
  server/utils/validation/updateCarValidation.js
Labels: Awaiting Review

#130 datebase edits
  package-lock.json
  package.json
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/cars/getCarsQuery.js
  server/database/queries/getCarDetailsQuery.js
  server/database/queries/getHomeReviews.js
  server/database/queries/getReview.js
  server/database/queries/postAdminCarsQueries.js
  server/database/queries/postReviewsRentalsId.js
  server/database/queries/rentals/addRentalQuery.js
  server/database/queries/rentals/checkDateTimeQuery.js
  server/database/queries/rentals/historyRintalsQuery.js
  server/database/queries/rentals/pendingRentalsQuery.js
  server/database/queries/updateCarData.js
  server/test/cars.test.js
Labels: Awaiting Review, BackEnd

#121 create a selector input component
  client/src/Components/Common/SelectorInput/Style.css
  client/src/Components/Common/SelectorInput/index.js
Labels: Changes Requested, FrontEnd, Component

#125 Loading spinner
  client/src/Components/Common/Spinner/index.js
Labels: Awaiting Review, FrontEnd, Component

#123 image card for brands and types
  client/.gitignore
  client/package-lock.json
  client/src/Components/Common/ImageCard/index.js
  client/src/Components/Common/ImageCard/style.css
  client/src/index.css
  package.json
Labels: Awaiting Review, FrontEnd, Component

#115 React route
  client/.gitignore
  client/package.json
  client/src/App/ProtectedRoute.js
  client/src/App/index.js
  client/src/App/use-auth.js
  client/src/index.js
  server/controllers/users/login.js
  server/controllers/users/signup.js
Labels: Awaiting Review, FrontEnd

#132 Common input
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/Components/Common/Button/index.jsx
  client/src/Components/Common/Input/index.jsx
  package-lock.json
  package.json
Labels: Awaiting Review, FrontEnd

#134 create car details component
  client/package.json
  client/src/Components/CarDetails/Style.css
  client/src/Components/CarDetails/inedx.js
  client/src/images/Vector.png
  client/src/images/door.png
  client/src/images/gear.png
Labels: Awaiting Review, FrontEnd, Component

#138 Alert component
  client/src/Components/Common/Alter/index.js
  client/src/Components/Common/Alter/style.css
  client/src/Components/Common/Button/index.jsx
Labels: Awaiting Review

#136 Car card component
  client/src/Components/Common/Button/index.jsx
  client/src/Components/Common/CarCard/Style.css
  client/src/Components/Common/CarCard/index.js
  client/src/images/seat.png
Labels: Awaiting Review, FrontEnd, Component

#135 Header Component
  client/src/App/style.css
  client/src/Components/Common/Header/index.jsx
  client/src/Components/Common/Header/style.css
Labels: Awaiting Review, FrontEnd

#141 Customers Opinion
  client/src/Components/Common/CustomersOpinion/index.jsx
Labels: Done, FrontEnd

#143 139 footer component
  client/src/App/index.js
  client/src/Components/Common/Footer/index.js
  client/src/Components/Common/Footer/style.css
Labels: Done

#142 Navbar Component
  client/package-lock.json
  client/src/App/index.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Common/Navbar/style.css
  client/src/images/Logo.png
Labels: In Progress, FrontEnd, Component

#149 Changes
  client/.gitignore
  client/src/App/ProtectedRoute.js
  client/src/App/index.js
  client/src/App/routes.js
  client/src/App/useAuth.js
  client/src/Components/Common/Alert/index.js
  client/src/Components/Common/Alert/style.css
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Common/Navbar/style.css
  client/src/Components/Common/SearchBox/index.js
  server/routes/index.js
  server/test/users.test.js
Labels: Awaiting Review

#152 Car details reviews
  client/src/App/index.js
  client/src/Components/Common/CarDetailsReviews/index.jsx
  client/src/Components/Common/CarDetailsReviews/style.css
Labels: Awaiting Review, FrontEnd

#150 Dashboard SideNav
  client/src/App/dashboardRoutes.js
  client/src/Components/Common/SideNav/index.js
  client/src/Components/Common/SideNav/style.css
  client/src/images/Logo2.png
Labels: Awaiting Review, Component

#155 Dashboard Dialog
  client/src/App/index.js
  client/src/Components/Common/DashboardDialog/index.js
  client/src/Components/Common/DashboardDialog/style.css
Labels: Awaiting Review

#144 13 rental form component
  client/src/Components/Common/DateTimePicker/index.js
  client/src/Components/Common/Input/index.js
  client/src/Components/Confirm/inedx.js
  client/src/Components/RentalForm/index.js
  client/src/Components/RentalForm/style.css
Labels: Awaiting Review, FrontEnd, Component

#158 sign up page
  client/src/App/index.js
  client/src/App/routes.js
  client/src/App/useAuth.js
  client/src/Components/Common/Button/index.jsx
  client/src/Components/Common/Input/index.js
  client/src/Pages/SignUp/index.js
  client/src/Pages/SignUp/style.css
  client/src/images/Logo3.png
  client/src/images/signup.png
Labels: Awaiting Review

#147 9 home page
  client/package.json
  client/src/App/index.js
  client/src/Components/Common/ImageCard/index.js
  client/src/Components/Common/SelectorInput/Style.css
  client/src/Components/Provider/Provider.js
  client/src/Pages/Home/index.js
  client/src/Pages/Home/style.css
  client/src/TypeContext/TypeContext.js
  server/database/config/fakeData.sql
  server/test/brands.test.js
Labels: Awaiting Review

#161 Filter component
  client/package-lock.json
  client/src/App/index.js
  client/src/Components/Common/DateTimePicker/index.js
  client/src/Components/Common/RadioTypes/index.js
  client/src/Components/Common/RadioTypes/style.css
  client/src/Components/Common/SelectorInput/index.js
  client/src/Components/Filter/index.js
  client/src/images/sedan.png
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/test/cars.test.js
Labels: Awaiting Review, FrontEnd, Component

#159 Dashboard Cars Page
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/Components/Common/DashboardDialog/style.css
  client/src/Components/Dashboard/Container/index.js
  client/src/Components/Dashboard/Container/style.css
  client/src/Components/Dashboard/DashboardDialog/index.js
  client/src/Components/Dashboard/DashboardDialog/style.css
  client/src/Components/Dashboard/DashboardTable/index.js
  client/src/Components/Dashboard/DashboardTable/style.css
  client/src/Components/Dashboard/SideNav/index.js
  client/src/Components/Dashboard/SideNav/style.css
  client/src/Pages/Dashboard/Cars/index.js
  client/src/Pages/Dashboard/Cars/style.css
  client/src/Pages/Dashboard/style.css
  server/database/queries/getCarByName.js
Labels: Done, FrontEnd

#160 Login Page
  client/src/App/routes.js
  client/src/App/useAuth.js
  client/src/Components/Common/Alert/index.js
  client/src/Components/Common/Button/index.jsx
  client/src/Pages/Login/index.js
  client/src/Pages/Login/style.css
  server/controllers/errors/serverError.js
Labels: Awaiting Review, FrontEnd

#151 Car Details Page
  client/src/App/index.js
  client/src/App/routes.js
  client/src/Components/CarDetails/Style.css
  client/src/Components/CarDetails/index.js
  client/src/Components/Common/Alert/style.css
  client/src/Components/Common/Footer/style.css
  client/src/Components/Common/Navbar/index.js
  client/src/Components/RentalForm/index.js
  client/src/Components/RentalForm/style.css
  client/src/Pages/CarDetails/index.js
  client/src/Pages/CarDetails/style.css
  client/src/Pages/CarDetailsPage/index.js
  client/src/Pages/CarDetailsPage/style.css
  client/src/Pages/SignUp/index.js
  client/src/Pages/SignUp/style.css
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/getCarDetailsQuery.js
  server/test/cars.test.js
Labels: Awaiting Review, FrontEnd

#164 Cars page
  client/src/Components/Common/CarCard/Style.css
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Filter/index.js
  client/src/Pages/Cars/index.js
  client/src/Pages/Home/index.js
Labels: Awaiting Review, FrontEnd, Route

#166 Handel Error Login
  client/src/Pages/Login/index.js
  client/src/Pages/Login/style.css
  client/src/Pages/SignUp/index.js
  client/src/Pages/SignUp/style.css
Labels: Awaiting Review, FrontEnd

#168 fix customer opinion style
  client/src/Pages/Home/index.js
  client/src/Pages/Home/style.css
Labels: Awaiting Review, FrontEnd

#170 Edit fake data
  client/src/Components/Filter/index.js
  client/src/Pages/Cars/index.js
  server/database/config/fakeData.sql
  server/test/brands.test.js
  server/test/cars.test.js
Labels: bug
